:rootdir: ../..
:sourcedir: ../../src/main/java
:source-highlighter: pygments


= Building a RESTful Web Service

This guide walks you through the process of creating a "hello world" RESTful web service with Spring.

== What you’ll build

You’ll build a service that will accept HTTP GET requests at:
....
http://localhost:8080/greeting
....

and respond with a JSON representation of a greeting:
....
{"id":1,"content":"Hello, World!"}
....

You can customize the greeting with an optional name parameter in the query string:
....
http://localhost:8080/greeting?name=User
....

The name parameter value overrides the default value of "World" and is reflected in the response:
....
{"id":1,"content":"Hello, User!"}
....

== What you’ll need

* About 15 minutes
* A favorite text editor or IDE
* JDK 1.8 or later
* Gradle 2.3+

include::1/main.adoc[]

include::2/main.adoc[]

include::3/main.adoc[]

include::4/main.adoc[]

== Test the service

Now that the service is up, visit http://localhost:8080/greeting, where you see:

....
{"id":1,"content":"Hello, World!"}
....

Provide a `name` query string parameter with http://localhost:8080/greeting?name=User.
Notice how the value of the `content` attribute changes from "Hello, World!" to "Hello User!":

....
{"id":2,"content":"Hello, User!"}
....

This change demonstrates that the `@RequestParam` arrangement in `GreetingController` is working as expected.
The `name` parameter has been given a default value of "World", but can always be explicitly overridden through the query string.

Notice also how the id attribute has changed from `1` to `2`.
This proves that you are working against the same `GreetingController` instance across multiple requests, and that its `counter` field is being incremented on each call as expected.

== Summary

Congratulations! You’ve just developed a RESTful web service with Spring.
